export const USER_MODAL_CREATE = "USER_MODAL_CREATE";
export const DRIVER_MODAL_CREATE = "DRIVER_MODAL_CREATE";
export const DRIVER_MODAL_DELETE = "DRIVER_MODAL_DELETE";
export const DRIVER_MODAL_UPDATE = "DRIVER_MODAL_UPDATE";
export const DRIVER_MODAL_STATUS = "DRIVER_MODAL_STATUS";
